config/routes.rb
Rails.application.routes.draw do
  get 'voting_ending_job/delete'
  root 'articles#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  resources :sessions
  resources :votes, only: :create
  resources :articles do
  resources :comments
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :votes

  validates :title, presence: true,
            length: { minimum: 5 }
  validates :text, presence: true,
            length: { minimum: 5 }
  validates :user_id, presence: true

  def voted_by?(user)
    votes.where(user_id: user.id).any?
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  
  has_secure_password
  has_many :article
  has_many :comments
  has_many :votes
  
  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :password, length: { minimum: 3 }

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

  validates :user_id, uniqueness: { scope: :article_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  protect_from_forgery with: :exception

  def current_user
    @user ||= User.find(session[:current_user_id]) if session[:current_user_id]
  end
  helper_method :current_user

  def authorize_user
    if current_user.nil?
      redirect_to root_path, notice: 'Не залогинен'
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authorize_user, only: [:create, :my, :destroy, :show]
  before_action :find_article, only:[:show, :edit,:update, :destroy]

 def index
    if params[:my]
      @name = "Мои статьи"
      @article = current_user.article.all
    elsif params[:all]
      @name = "Все статьи"
      @article = Article.all
    else
      @name = "Последние статьи"
      @article = Article.select(params[:id]).first(10).reverse
    end
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.create(article_params.merge({user_id: current_user}))
    @article.user = current_user
    if @article.save
      flash["alert-succes"] = "Статья добавлена"
      redirect_to article_path(@article.id)
     else
      flash[:error] = 'Ошибка!'
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to article_path(@article.id)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path, notice: 'Статья удалена'
  end

  private

    def find_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    @comment = Comment.new
  end

  def show
    @comment = Comment.find(params[:id])
  end


  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
  
    def comment_params
      params.require(:comment).permit(:user_id, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to root_url, notice: 'Добро пожаловать!'
    else
      flash.now.alert = 'Email или пароль не верный'
      render "new"
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new 
  end

  def create
    @user = User.new(permitted_params)
    if @user.save
      flash[:success] = "Спасибо что зарегистрировались!"
      session[:user_id] = @user.id
      redirect_to root_url
    else
      flash[:error] = 'Ошибка!'
      render 'new'
    end
  end

  private

  def permitted_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation, :avatar)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  
  before_filter :authorize_user
  
  def create
    vote = current_user.votes.create(permitted_params)
    votes = Vote.where(permitted_params).count
    article = vote.article
    flash["alert-success"] = 'Спасибо! Ваш голос учтен'
    redirect_to vote.article
  end

  private

  def permitted_params
    params.permit(:article_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)
  def bootstrap_class_for flash_type
      { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
      flash.each do |msg_type, message|
        concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
                concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
                concat message 
              end)
      end
      nil
  end

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      tag_class = options.extract!(:class)[:class]
      tag_options = {
        class: "alert fade in alert-#{type} #{tag_class}"
      }.merge(options)

      close_button = content_tag(:button, raw("&times;"), type: "button", class: "close", "data-dismiss" => "alert")

      Array(message).each do |msg|
        text = content_tag(:div, close_button + msg, tag_options)
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
 def signed_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <%= form_for @article do |f| %>
    <% if @article.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% @article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title, 'Название' %><br />
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :text, 'Описание' %><br />
      <%= f.text_area :text, class: 'form-control' %>
    </div>

    <div class="row btn-row">
        <div class="actions col-xs-2 btn-save">
          <%= submit_tag 'Cохранить', class: 'btn btn-success' %>
        </div>
        <div class="btn btn-default col-xs-2 col-xs-offset-8 btn-back"> <%= link_to 'Назад', articles_path %> 
        </div>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="container">
  <h1>Изменить статью</h1>
</div>
<%= render 'form' %>
 

app/views/articles/index.html.erb
 <div class="content container ">
    <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <table class="table table-striped">
       <tr>
        <td class="col-xs-1"><strong>№</strong></td>
        <td class="col-xs-6"><strong>Статья</strong></td>
        <td><strong>Автор</strong></td>
        <td><strong>Голоса</strong></td>
        <td><strong>Дата создания</strong></td>
        <td colspan="2" align="center"><strong>Действия</strong></td>

      </tr>


      <% if @article %>
            <% @article.each_with_index do |article, index| %>
            <tr>
              <td><%= index + 1 %> </td>
              <td><%= link_to article.title, article %></td>
                <% unless article.user.nil? %>
                <td><%= article.user.first_name%></td>
                <td><%= article.votes.count %></td>
                <td><%= article.created_at.strftime('%d/%m/%Y %H:%M') %></td>
                <td><div class="actions">
                  <%= link_to 'Редактировать', edit_article_path(@article) %> 
                </div></td>
                <td><div class="actions">
                  <%= link_to 'Удалить', article,
                                        method: :delete,
                                        data: { confirm: 'Вы уверены?' } %> 
                </div></td>  
            </tr>
                <% end %> 
              <% end %>
            <% end %>
    </table>
   

app/views/articles/new.html.erb
<div class="container">
  <h1>Новая статья</h1>
</div>
 
<%= render 'form' %>
 

app/views/articles/show.html.erb
<div class="container">
  <div class="header-title">
    <%= image_tag @article.user.avatar.url(:thumb) %>
    <h3 class="page-header title-text"> <%= @article.title %></h3>
    <p>
      <%= @article.created_at.strftime('%d/%m/%Y %H:%M')  %>
    </p>
  </div>
  <p class="sub-header"> <%= @article.text %></p>

  <p>
    <% if @article.voted_by?(current_user) %>
      Вы уже проголосовали за данную статью
    <% else %>
      <%= button_to('Проголосовать', votes_path({ article_id: @article.id })) %>
    <% end %>
  </p>

  <p>
    <b>Голосов:</b>
    <%= @article.votes.count %>
  </p>
    
  <%= render "comments/show" %>
  <%= render "comments/new" %>
</div>

app/views/comments/_new.html.erb
<div class="container">
  <div class="add-comment">
    <h4>Добавить комметарий:</h4>
    <%= form_for([@article, @article.comments.build]) do |f| %>
      <%= image_tag current_user.avatar.url(:thumb) %>
      <p>
        <%= f.label :Имя %>
        <td><%= current_user.first_name%> </td>
      </p> 

      <div class="form-group">
        <%= f.label :Комментарий %><br>
        <%= f.text_area :body, class: 'form-control' %>
        <%= f.hidden_field :user_id, :value => current_user.id  %>
      </div>
  </div> 

  <div class="buttons container row"> 
    <div class="actions col-xs-2 btn-save">
      <%= submit_tag 'Cоздать Комментарий', class: 'btn btn-success' %>
    </div>
    <% end %>
    <div class="btn btn-default col-xs-2 col-xs-offset-8 btn-back "><%= link_to 'Назад', articles_path %> </div>
  </div>
</div>

app/views/comments/_show.html.erb
<div class="container">
  <div class="coment">
    <% @article.comments.each do |comment| %>
    <p class="page-header name">
    <%= image_tag comment.user.avatar.url(:thumb) %>
      <strong>Имя:</strong>
      <td><%= @article.user.first_name%> </td>
    </p>
    <p>
      <strong>Комментарий:</strong>
      <%= comment.body %>
    </p>
  </div>

  <p class="btn btn-danger btn-sm">
    <%= link_to 'Удалить комментарий', [comment.article, comment],
                 method: :delete,
                 data: { confirm: 'Вы уверены?' } %>
  </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head> 
  <title>Блог</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="container" class="container">
    <div id="user_header" align="right" class="navbar-default row">
      <table class="table container">
        <div class="root_path">
          <p class="col-xs-6 h4 title " align="left"><%= link_to "Мой блог", root_path %></p>
        </div>
        <% if current_user %>
          <div id="avatar" class="img-circle">
            <%= image_tag current_user.avatar.url(:thumb) %>
          </div>
            <div class="col-xs-6 row pull-right">
              <span class="col-xs-9 user-name"><%= current_user.email %></span>
            <div class="btn btn-default col-xs-3"><%= link_to "Выйти", logout_path %></div>
              <% else %>
              <div class="btn btn-default"><%= link_to "Зарегистрироваться", new_user_path %> </div>
              <div class="btn btn-default"><%= link_to "Войти", new_session_path %></div>
           <% end %>
          </div>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12"> &nbsp</div>
  </div>
  <div class="container">
    <div class="col-xs-3">
      <h3 class="page-header "><%= @name %></h3>
    </div>
    <div class="sidebar col-xs-3 col-xs-offset-6 navbar navbar-default">
      <ul>
        <li><%= link_to 'Все статьи', '/?all=true' %></li>
          <% if current_user %>
          <li><%= link_to 'Создать статью', new_article_path %></li>
          <li><%= link_to 'Мои статьи', '/?my=true' %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>
  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, id: "flash_#{:last_name}" %>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/users/new.html.erb
<div class="container">
<h1>Регистрация</h1>
<%= form_for @user, url: users_path, html: { multipart: true } do |f| %>
  <% if @user.errors.any? %>
    <div class="error_massages">
      <h2> Форма is invalid </h2>
      <ul>
        <% @user.errors.full_messages.each do |messages| %>
          <li><%= messages %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.file_field :avatar %>
  </div>
 
  <div class="form-group" style="width: 50%">
    <%= f.label :email %><br />
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group" style="width: 50%">
    <%= f.label :first_name, 'Имя'%><br />
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group" style="width: 50%">
    <%= f.label :last_name, "Фамилия" %><br />
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group" style="width: 50%">
    <%= f.label :password, 'Пароль' %><br />
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group" style="width: 50%">
    <%= f.label :password_confirmation, 'Подтверждение пароля' %><br />
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class="actions"><%= f.submit "Зарегистрироваться", class: 'btn btn-primary' %></div>
<% end %> 
</div>